---

- name: Update pip & related tools
  pip:
    name:
      - pip
      - setuptools
      - wheel
      - attrs
      - importlib-metadata
      - packaging
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: Reload application

- name: Copy requirements.txt
  copy:
    src: "{{ role_path }}/files/requirements.txt"
    dest: "{{ virtualenv_path }}/requirements.txt"

- name: Install Python dependencies from requirements.txt
  pip:
    requirements: "{{ virtualenv_path }}/requirements.txt"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: Reload application

- name: Install Django with configurable version
  pip:
    name: "{{ openwisp2_django_version }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: Reload application
  tags:
    - molecule-idempotence-notest

- name: Install openwisp2 controller
  pip:
    name: "{{ openwisp2_controller_version }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: Reload application
  tags:
    - molecule-idempotence-notest

- name: Install openwisp2 network topology
  when: openwisp2_network_topology
  pip:
    name: "{{ openwisp2_network_topology_version }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: Reload application
  tags:
    - molecule-idempotence-notest

- name: Install openwisp2 firmware upgrader
  when: openwisp2_firmware_upgrader
  pip:
    name: "{{ openwisp2_firmware_upgrader_version }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: Reload application
  tags:
    - molecule-idempotence-notest

- name: Install openwisp2 monitoring
  when: openwisp2_monitoring
  pip:
    name: "{{ openwisp2_monitoring_version }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: Reload application
  tags:
    - molecule-idempotence-notest

- name: Install openwisp2 radius
  when: openwisp2_radius
  pip:
    name: "{{ openwisp2_radius_version }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: Reload application
  tags:
    - molecule-idempotence-notest

- name: Install extra python packages
  pip:
    name: "{{ openwisp2_extra_python_packages }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
  when: openwisp2_extra_python_packages | length > 0
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: Reload application
  tags: [extra_pip]

- name: Install psycopg2 for PostgreSQL backend
  when: openwisp2_database.engine in ["django.db.backends.postgresql", "django.contrib.gis.db.backends.postgis"]
  pip:
    name: psycopg2-binary
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: Reload application

- name: Install MySQL-python for Python 2
  when: 
    - openwisp2_database.engine in ["django.db.backends.mysql", "django.contrib.gis.db.backends.mysql"]
    - openwisp2_python is version('3.0', '<')
  pip:
    name: MySQL-python
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: Reload application

- name: Install mysqlclient for Python 3
  when:
    - openwisp2_database.engine in ["django.db.backends.mysql", "django.contrib.gis.db.backends.mysql"]
    - openwisp2_python is version('3.0', '>=')
  pip:
    name: mysqlclient
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: Reload application

- name: Install raven (sentry client)
  when: openwisp2_sentry.get('dsn')
  pip:
    name: raven
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: Reload application

- name: Install django-celery-email
  when: openwisp2_email_backend == "djcelery_email.backends.CeleryEmailBackend"
  pip:
    name: django-celery-email
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: Reload application
